//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VISION.WebService.IzibizSrvAuthentication {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationPortBinding", Namespace="http://schemas.i2i.com/ei/wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REQUEST_INFOType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PARTINFO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LOV_VALUEType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REQUEST))]
    public partial class AuthenticationWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGibUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAuthorizationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticationWS() {
            this.Url = global::VISION.Properties.Settings.Default.VISION_WebService_IzibizSrvAuthentication_AuthenticationWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event GetGibUserListCompletedEventHandler GetGibUserListCompleted;
        
        /// <remarks/>
        public event CheckUserCompletedEventHandler CheckUserCompleted;
        
        /// <remarks/>
        public event GetUserAuthorizationCompletedEventHandler GetUserAuthorizationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LoginResponse", Namespace="http://schemas.i2i.com/ei/wsdl")]
        public LoginResponse Login([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")] LoginRequest LoginRequest) {
            object[] results = this.Invoke("Login", new object[] {
                        LoginRequest});
            return ((LoginResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(LoginRequest LoginRequest) {
            this.LoginAsync(LoginRequest, null);
        }
        
        /// <remarks/>
        public void LoginAsync(LoginRequest LoginRequest, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        LoginRequest}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LogoutResponse", Namespace="http://schemas.i2i.com/ei/wsdl")]
        public LogoutResponse Logout([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")] LogoutRequest LogoutRequest) {
            object[] results = this.Invoke("Logout", new object[] {
                        LogoutRequest});
            return ((LogoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync(LogoutRequest LogoutRequest) {
            this.LogoutAsync(LogoutRequest, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(LogoutRequest LogoutRequest, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        LogoutRequest}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetGibUserListResponse", Namespace="http://schemas.i2i.com/ei/wsdl")]
        public GetGibUserListResponse GetGibUserList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")] GetGibUserListRequest GetGibUserListRequest) {
            object[] results = this.Invoke("GetGibUserList", new object[] {
                        GetGibUserListRequest});
            return ((GetGibUserListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetGibUserListAsync(GetGibUserListRequest GetGibUserListRequest) {
            this.GetGibUserListAsync(GetGibUserListRequest, null);
        }
        
        /// <remarks/>
        public void GetGibUserListAsync(GetGibUserListRequest GetGibUserListRequest, object userState) {
            if ((this.GetGibUserListOperationCompleted == null)) {
                this.GetGibUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGibUserListOperationCompleted);
            }
            this.InvokeAsync("GetGibUserList", new object[] {
                        GetGibUserListRequest}, this.GetGibUserListOperationCompleted, userState);
        }
        
        private void OnGetGibUserListOperationCompleted(object arg) {
            if ((this.GetGibUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGibUserListCompleted(this, new GetGibUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CheckUserResponse", Namespace="http://schemas.i2i.com/ei/wsdl")]
        public CheckUserResponse CheckUser([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")] CheckUserRequest CheckUserRequest) {
            object[] results = this.Invoke("CheckUser", new object[] {
                        CheckUserRequest});
            return ((CheckUserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserAsync(CheckUserRequest CheckUserRequest) {
            this.CheckUserAsync(CheckUserRequest, null);
        }
        
        /// <remarks/>
        public void CheckUserAsync(CheckUserRequest CheckUserRequest, object userState) {
            if ((this.CheckUserOperationCompleted == null)) {
                this.CheckUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserOperationCompleted);
            }
            this.InvokeAsync("CheckUser", new object[] {
                        CheckUserRequest}, this.CheckUserOperationCompleted, userState);
        }
        
        private void OnCheckUserOperationCompleted(object arg) {
            if ((this.CheckUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserAuthorizationResponse", Namespace="http://schemas.i2i.com/ei/wsdl")]
        public GetUserAuthorizationResponse GetUserAuthorization([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")] GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            object[] results = this.Invoke("GetUserAuthorization", new object[] {
                        GetUserAuthorizationRequest});
            return ((GetUserAuthorizationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAuthorizationAsync(GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            this.GetUserAuthorizationAsync(GetUserAuthorizationRequest, null);
        }
        
        /// <remarks/>
        public void GetUserAuthorizationAsync(GetUserAuthorizationRequest GetUserAuthorizationRequest, object userState) {
            if ((this.GetUserAuthorizationOperationCompleted == null)) {
                this.GetUserAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAuthorizationOperationCompleted);
            }
            this.InvokeAsync("GetUserAuthorization", new object[] {
                        GetUserAuthorizationRequest}, this.GetUserAuthorizationOperationCompleted, userState);
        }
        
        private void OnGetUserAuthorizationOperationCompleted(object arg) {
            if ((this.GetUserAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAuthorizationCompleted(this, new GetUserAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginRequest : REQUEST {
        
        private string uSER_NAMEField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER_NAME {
            get {
                return this.uSER_NAMEField;
            }
            set {
                this.uSER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUserAuthorizationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetGibUserListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_HEADERType REQUEST_HEADER {
            get {
                return this.rEQUEST_HEADERField;
            }
            set {
                this.rEQUEST_HEADERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_HEADERType {
        
        private string sESSION_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private long iNTL_TXN_IDField;
        
        private bool iNTL_TXN_IDFieldSpecified;
        
        private long iNTL_PARENT_TXN_IDField;
        
        private bool iNTL_PARENT_TXN_IDFieldSpecified;
        
        private System.DateTime aCTION_DATEField;
        
        private bool aCTION_DATEFieldSpecified;
        
        private CHANGE_INFOType cHANGE_INFOField;
        
        private string rEASONField;
        
        private string aPPLICATION_NAMEField;
        
        private string hOSTNAMEField;
        
        private string cHANNEL_NAMEField;
        
        private string sIMULATION_FLAGField;
        
        private string cOMPRESSEDField;
        
        private ATTRIBUTESTYPE[] aTTRIBUTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_TXN_IDSpecified {
            get {
                return this.iNTL_TXN_IDFieldSpecified;
            }
            set {
                this.iNTL_TXN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long INTL_PARENT_TXN_ID {
            get {
                return this.iNTL_PARENT_TXN_IDField;
            }
            set {
                this.iNTL_PARENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_PARENT_TXN_IDSpecified {
            get {
                return this.iNTL_PARENT_TXN_IDFieldSpecified;
            }
            set {
                this.iNTL_PARENT_TXN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ACTION_DATE {
            get {
                return this.aCTION_DATEField;
            }
            set {
                this.aCTION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACTION_DATESpecified {
            get {
                return this.aCTION_DATEFieldSpecified;
            }
            set {
                this.aCTION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CHANGE_INFOType CHANGE_INFO {
            get {
                return this.cHANGE_INFOField;
            }
            set {
                this.cHANGE_INFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string APPLICATION_NAME {
            get {
                return this.aPPLICATION_NAMEField;
            }
            set {
                this.aPPLICATION_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string HOSTNAME {
            get {
                return this.hOSTNAMEField;
            }
            set {
                this.hOSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CHANNEL_NAME {
            get {
                return this.cHANNEL_NAMEField;
            }
            set {
                this.cHANNEL_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SIMULATION_FLAG {
            get {
                return this.sIMULATION_FLAGField;
            }
            set {
                this.sIMULATION_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMPRESSED {
            get {
                return this.cOMPRESSEDField;
            }
            set {
                this.cOMPRESSEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATTRIBUTES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ATTRIBUTESTYPE[] ATTRIBUTES {
            get {
                return this.aTTRIBUTESField;
            }
            set {
                this.aTTRIBUTESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class CHANGE_INFOType {
        
        private System.DateTime cDATEField;
        
        private long cPOSITION_IDField;
        
        private long cUSER_IDField;
        
        private System.DateTime uDATEField;
        
        private bool uDATEFieldSpecified;
        
        private long uPOSITION_IDField;
        
        private bool uPOSITION_IDFieldSpecified;
        
        private long uUSER_IDField;
        
        private bool uUSER_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime CDATE {
            get {
                return this.cDATEField;
            }
            set {
                this.cDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long CPOSITION_ID {
            get {
                return this.cPOSITION_IDField;
            }
            set {
                this.cPOSITION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long CUSER_ID {
            get {
                return this.cUSER_IDField;
            }
            set {
                this.cUSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime UDATE {
            get {
                return this.uDATEField;
            }
            set {
                this.uDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UDATESpecified {
            get {
                return this.uDATEFieldSpecified;
            }
            set {
                this.uDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long UPOSITION_ID {
            get {
                return this.uPOSITION_IDField;
            }
            set {
                this.uPOSITION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPOSITION_IDSpecified {
            get {
                return this.uPOSITION_IDFieldSpecified;
            }
            set {
                this.uPOSITION_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long UUSER_ID {
            get {
                return this.uUSER_IDField;
            }
            set {
                this.uUSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UUSER_IDSpecified {
            get {
                return this.uUSER_IDFieldSpecified;
            }
            set {
                this.uUSER_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class ATTRIBUTESTYPE {
        
        private string nAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_INFOType {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType rEQUEST_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_HEADERType REQUEST_HEADER {
            get {
                return this.rEQUEST_HEADERField;
            }
            set {
                this.rEQUEST_HEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_RETURNType REQUEST_RETURN {
            get {
                return this.rEQUEST_RETURNField;
            }
            set {
                this.rEQUEST_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_ERRORType REQUEST_ERROR {
            get {
                return this.rEQUEST_ERRORField;
            }
            set {
                this.rEQUEST_ERRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_RETURNType {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int rETURN_CODEField;
        
        private string[] wARNINGSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RETURN_CODE {
            get {
                return this.rETURN_CODEField;
            }
            set {
                this.rETURN_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WARNINGS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] WARNINGS {
            get {
                return this.wARNINGSField;
            }
            set {
                this.wARNINGSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_ERRORType {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int eRROR_CODEField;
        
        private string eRROR_SHORT_DESField;
        
        private string eRROR_LONG_DESField;
        
        private string sTACKTRACEField;
        
        private int eRROR_ELEMENT_INDEXField;
        
        private bool eRROR_ELEMENT_INDEXFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ERROR_CODE {
            get {
                return this.eRROR_CODEField;
            }
            set {
                this.eRROR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERROR_SHORT_DES {
            get {
                return this.eRROR_SHORT_DESField;
            }
            set {
                this.eRROR_SHORT_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERROR_LONG_DES {
            get {
                return this.eRROR_LONG_DESField;
            }
            set {
                this.eRROR_LONG_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STACKTRACE {
            get {
                return this.sTACKTRACEField;
            }
            set {
                this.sTACKTRACEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ERROR_ELEMENT_INDEX {
            get {
                return this.eRROR_ELEMENT_INDEXField;
            }
            set {
                this.eRROR_ELEMENT_INDEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERROR_ELEMENT_INDEXSpecified {
            get {
                return this.eRROR_ELEMENT_INDEXFieldSpecified;
            }
            set {
                this.eRROR_ELEMENT_INDEXFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class PARTINFO {
        
        private string vKNField;
        
        private string iDENTIFIERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string VKN {
            get {
                return this.vKNField;
            }
            set {
                this.vKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string IDENTIFIER {
            get {
                return this.iDENTIFIERField;
            }
            set {
                this.iDENTIFIERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class LOV_VALUEType {
        
        private long lOV_IDField;
        
        private string lOV_CODEField;
        
        public LOV_VALUEType() {
            this.lOV_CODEField = "\'N\'";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long LOV_ID {
            get {
                return this.lOV_IDField;
            }
            set {
                this.lOV_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("\'N\'")]
        public string LOV_CODE {
            get {
                return this.lOV_CODEField;
            }
            set {
                this.lOV_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GIBUSER {
        
        private string iDENTIFIERField;
        
        private string aLIASField;
        
        private string tITLEField;
        
        private string tYPEField;
        
        private string rEGISTER_TIMEField;
        
        private string uNITField;
        
        private string aLIAS_CREATION_TIMEField;
        
        private string aCCOUNT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDENTIFIER {
            get {
                return this.iDENTIFIERField;
            }
            set {
                this.iDENTIFIERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ALIAS {
            get {
                return this.aLIASField;
            }
            set {
                this.aLIASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGISTER_TIME {
            get {
                return this.rEGISTER_TIMEField;
            }
            set {
                this.rEGISTER_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ALIAS_CREATION_TIME {
            get {
                return this.aLIAS_CREATION_TIMEField;
            }
            set {
                this.aLIAS_CREATION_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT_TYPE {
            get {
                return this.aCCOUNT_TYPEField;
            }
            set {
                this.aCCOUNT_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserResponse {
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private GIBUSER[] uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIBUSER[] USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationResponse {
        
        private AUTHORIZED aUTHORIZEDField;
        
        private bool aUTHORIZEDFieldSpecified;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private PRODUCT[] pRODUCT_LISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AUTHORIZED AUTHORIZED {
            get {
                return this.aUTHORIZEDField;
            }
            set {
                this.aUTHORIZEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AUTHORIZEDSpecified {
            get {
                return this.aUTHORIZEDFieldSpecified;
            }
            set {
                this.aUTHORIZEDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PRODUCT[] PRODUCT_LIST {
            get {
                return this.pRODUCT_LISTField;
            }
            set {
                this.pRODUCT_LISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum AUTHORIZED {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT {
        
        /// <remarks/>
        EINVOICE,
        
        /// <remarks/>
        EARCHIVE,
        
        /// <remarks/>
        EDESPATCH,
        
        /// <remarks/>
        CREDITNOTE,
        
        /// <remarks/>
        RECONCILIATION,
        
        /// <remarks/>
        CONNECTOR,
        
        /// <remarks/>
        ELEDGER,
        
        /// <remarks/>
        ELEDGERARCHIVE,
        
        /// <remarks/>
        EINVOICEARCHIVE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("EINVOICEARCHIVE")]
        EINVOICEARCHIVE1,
        
        /// <remarks/>
        ESMM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListResponse {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTENT", typeof(base64Binary), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ERROR_TYPE", typeof(REQUEST_ERRORType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutResponse {
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_RETURNType REQUEST_RETURN {
            get {
                return this.rEQUEST_RETURNField;
            }
            set {
                this.rEQUEST_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginResponse {
        
        private string sESSION_IDField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserRequest : REQUEST {
        
        private GIBUSER uSERField;
        
        private string dOCUMENT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GIBUSER USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationRequest : REQUEST {
        
        private PRODUCT pRODUCTField;
        
        private PRODUCT_DETAIL_FLAG pRODUCT_DETAIL_FLAGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PRODUCT PRODUCT {
            get {
                return this.pRODUCTField;
            }
            set {
                this.pRODUCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PRODUCT_DETAIL_FLAG PRODUCT_DETAIL_FLAG {
            get {
                return this.pRODUCT_DETAIL_FLAGField;
            }
            set {
                this.pRODUCT_DETAIL_FLAGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT_DETAIL_FLAG {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListRequest : REQUEST {
        
        private GetGibUserListRequestTYPE tYPEField;
        
        private string dOCUMENT_TYPEField;
        
        private System.DateTime rEGISTER_TIME_STARTField;
        
        private bool rEGISTER_TIME_STARTFieldSpecified;
        
        public GetGibUserListRequest() {
            this.tYPEField = GetGibUserListRequestTYPE.XML;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(GetGibUserListRequestTYPE.XML)]
        public GetGibUserListRequestTYPE TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime REGISTER_TIME_START {
            get {
                return this.rEGISTER_TIME_STARTField;
            }
            set {
                this.rEGISTER_TIME_STARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REGISTER_TIME_STARTSpecified {
            get {
                return this.rEGISTER_TIME_STARTFieldSpecified;
            }
            set {
                this.rEGISTER_TIME_STARTFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum GetGibUserListRequestTYPE {
        
        /// <remarks/>
        CSV,
        
        /// <remarks/>
        XML,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutRequest : REQUEST {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LogoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LogoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetGibUserListCompletedEventHandler(object sender, GetGibUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGibUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGibUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetGibUserListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetGibUserListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CheckUserCompletedEventHandler(object sender, CheckUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckUserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckUserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetUserAuthorizationCompletedEventHandler(object sender, GetUserAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserAuthorizationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserAuthorizationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591